[package]
name = "drawbridge"
version = "0.1.0"
authors = ["Profian Inc"]
edition = "2021"

[workspace]
members = [
    "crates/byte",
    "crates/client",
    "crates/hash",
    "crates/jose",
    "crates/server",
    "crates/type",
]

[dependencies]
# Internal dependencies
drawbridge-byte = { path = "./crates/byte" }
drawbridge-client = { path = "./crates/client", optional = true }
drawbridge-hash = { path = "./crates/hash" }
drawbridge-jose = { path = "./crates/jose" }
drawbridge-server = { path = "./crates/server", optional = true }
drawbridge-type = { path = "./crates/type" }

# External dependencies
anyhow = { version = "1.0.57", default-features = false, features = ["std"], optional = true }
async-std = { version = "1.11.0", default-features = false, features = ["attributes"], optional = true }
clap = { version = "3.2.3", default-features = false, features = ["derive", "std"], optional = true }
env_logger = { version = "0.9.0", default-features = false, features = ["atty", "termcolor"], optional = true }
futures = { version = "0.3.21", default-features = false, optional = true }
log = { version = "0.4.17", default-features = false, features = ["release_max_level_debug"], optional = true }
toml = { version = "0.5.9", default-features = false, optional = true }

[dev-dependencies]
# Internal dependencies
drawbridge-client = { path = "./crates/client" }
drawbridge-server = { path = "./crates/server" }
drawbridge-type = { path = "./crates/type", features = ["server"] }

# External dependencies
async-h1 = { version = "2.3.3", default-features = false }
async-std = { version = "1.11.0", default-features = false, features = ["attributes", "default"] }
env_logger = { version = "0.9.0", default-features = false, features = ["atty", "termcolor"] }
futures = { version = "0.3.21", default-features = false }
http-types = { version = "2.12.0", default-features = false }
openidconnect = { version = "2.3.1", default-features = false }
rustls = { version = "0.20.6", default-features = false }
rustls-pemfile = { version = "1.0.0", default-features = false }
serde_json = { version = "1.0.79", default-features = false, features = ["std"] }
tempfile = { version = "3.3.0", default-features = false }

[features]
default = ["bin"]
bin = [
    "server",

    "anyhow",
    "async-std",
    "clap",
    "env_logger",
    "futures",
    "log",
    "toml"
]
client = ["drawbridge-client"]
server = ["drawbridge-server", "drawbridge-type/server"]
